import React, { FC } from 'react';
import { ReactNode } from 'react';
import './globals.css';
import { Metadata } from 'next';


interface Props {
  children:ReactNode;
}
export const metadata:Metadata = {
  title:'Space Portfolio',
  description:'Generated by create n'
}

const RootLayer: FC<Props> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
};

export default RootLayer;